var vortListo = [

  "abelo", "aĉeti", "adiaŭ", "adresaro", "adreso", "advokato", "aero",
  "aerodinamika", "aerostato", "afabla", "afero", "agento", "aglo", "agmaniero",
  "agokula", "agrabla", "akcepti", "akcidento", "akra", "akrido", "aktorino",
  "aktualigi", "akvo", "alia", "aliflanke", "aligatoro", "aliĝi", "alirebla",
  "alklaki", "allogi", "almenaŭ", "alŝuti", "alta", "alveni", "amara", "amaso",
  "ambaŭ", "ambaŭflanke", "ambulanco", "amikeco", "amiko", "anaso", "angora",
  "angulo", "animo", "ankaŭ", "ankoraŭ", "ankro", "anstataŭ", "antaŭ",
  "antibakterio", "aparta", "apenaŭ", "aperi", "apetito", "apoteko", "aprilo",
  "apud", "arakido", "araneo", "arbaro", "arboj", "arbusto", "arego", "areto",
  "arĝento", "arkitekto", "armilo", "artefarita", "arto", "astronomo", "ataki",
  "ateismo", "atendi", "atenta", "atentinde", "atesti", "aŭdi", "aŭguro", "aŭgusto",
  "aŭskulti", "aŭto", "aŭtomobilo", "aŭtoritato", "aŭtuno", "avelo", "aviadilo",
  "avino", "bakterio", "baldaŭ", "baleno", "banĉambro", "bandaĝo", "bankisto",
  "bari", "batali", "bati", "bebo", "bela", "beno", "benzinujo", "besto",
  "bestoĝardeno", "bezoni", "bibliotekisto", "biciklo", "biero", "bildo",
  "biokemiisto", "biologo", "birdo", "blanka", "blasfemi", "blinda", "blonda",
  "blua", "boato", "bofratino", "bofrato", "bogepatroj", "bona", "boneco",
  "bopatrino", "bopatro", "bordo", "botanikisto", "bovaĵo", "bovino", "bovlo",
  "bovo", "bradipo", "brako", "brakumi", "branĉo", "brakumi", "brando", "brili",
  "bronzo", "brui", "bruli", "bruna", "bubo", "buso", "buŝo", "butiko", "butikumi",
  "ĉambro", "ĉapelo", "ĉarmita", "ĉasi", "ĉefministro", "ĉefurbo", "celi", "ĉemizo",
  "centono", "certa", "certigi", "certigo", "cervo", "ĉevalo", "cidro", "ĉielo",
  "cigno", "cikatro", "ĉirkaŭ", "ĉirkaŭrigadi", "ĉisi", "civilizo", "ĉokolado",
  "cunamo", "danci", "dancistino", "danki", "dankema", "daŭri", "dece", "decembro",
  "defio", "dekstra", "delogaĵo", "demandi", "denove", "densa", "dentisto", "dento",
  "dentoj", "depost", "detalo", "devi", "devo", "deziri", "diamanto", "dianto",
  "dika", "dimanĉo", "diplomo", "direkto", "direktoro", "diri", "disko", "disĵeti",
  "disponebla", "dissendi", "diversa", "doganisto", "dolĉa", "doloro", "domaĉo",
  "domego", "domo", "doni", "dormĉambro", "dormi", "drinkejo", "dubi", "duobla",
  "duoblo", "duona", "edziĝi", "edzino", "edzo", "ekbrili", "ekkrii", "ekonomikisto",
  "ekrano", "ekscita", "ekster", "ekzemplo", "ekzerci", "elefanto", "elekti",
  "elŝuti", "elteni", "eluzi", "enterigita", "entrepeni", "entreprenisto",
  "entrudinto", "entuziasmo", "enviinda", "epidemio", "episkopino", "eraro",
  "erupcio", "esperanto", "espero", "esti", "estanteco", "estinteco", "estonteco",
  "etendi", "etikedo", "etnografo", "facila", "fajfi", "fajro", "fajrobrigadisto",
  "fali", "falko", "familiara", "familio", "fantazio", "fari", "farti", "februaro",
  "feino", "feliĉa", "fenestro", "fermi", "fermita", "fero", "fervorulo", "festi",
  "festivalo", "fianĉo", "fiero", "fifama", "filino", "filo", "filozofo", "fingro",
  "fingropremaĵo", "fini", "firme", "fiŝaĵo", "fiŝoj", "fizikisto", "fiziologo",
  "flamo", "flanko", "flava", "flegistino", "flirtumi", "floristo", "floro",
  "flua", "flugi", "flustri", "fojo", "foko", "folio", "foresto", "forgesi",
  "forkapti", "forko", "formo", "formorti", "forpreni", "forta", "fotinda",
  "fotistino", "frapi", "fratino", "frato", "fraŭlo", "frekventi", "fremda",
  "fripono", "frizisto", "fromaĝo", "frua", "frukto", "frunto", "fuĝi", "fulmo",
  "fulmotondro", "fumo", "fungoj", "fuŝi", "futbalo", "gaja", "gajni", "ĝangalo",
  "ĝardeno", "gazeto", "gefiloj", "ĝemspiro", "gepatroj", "gesinjoroj", "genuo",
  "geografio", "geografo", "ginekologo", "glacio", "glano", "glaso", "glavingo",
  "glisaviadilo", "globo", "ĝoji", "golo", "grafikisto", "granda", "gratulon",
  "grava", "grilo", "griza", "ĝusta", "ĝuste", "gusto", "gustumi", "halti",
  "hararo", "havebla", "havi", "hazarda", "hejmtasko", "hejmo", "hela", "heliko",
  "helikoptero", "helpu", "hepato", "herbo", "heroo", "hidrologo", "hieraŭ",
  "hipopotamo", "historiisto", "historio", "hodiaŭ", "homaro", "homoj", "horo",
  "ĥoro", "hotelo", "humila", "hundo", "hundokaptisto", "ideo", "imagi",
  "improvizu", "infano", "inĝeniero", "injekto", "inkvizicio", "insekto", "instrui",
  "instruistino", "instruisto", "inter", "interno", "interesa", "interna",
  "interrompi", "interreto", "inundo", "inventisto", "jaĥto", "jako", "ĵaluza",
  "januaro", "ĵeti", "juĝisto", "juglando", "julio", "juna", "junio", "junulo",
  "ĵuri", "juristo", "ĵurnalo", "justa", "juvelisto", "kablo", "kafo", "kalkuli",
  "kamelo", "kamioneto", "kamiono", "kampo", "kanario", "kandelingo", "kanguruo",
  "kanjono", "kanti", "kapo", "kapro", "kapti", "kara", "kartografo", "kaŝi",
  "katastrofo", "katido", "kaŭĉuko", "kaŭzo", "kelka", "kelnerino", "kemiisto",
  "kien", "kirurgio", "klaki", "klara", "klaŭno", "klimatizado", "klimato", "klini",
  "kliniigi", "klingo", "klopodi", "klubo", "knabaĝo", "knabino", "knabo",
  "kokcinelo", "kokinaĵo", "kokino", "kokoso", "kolekti", "kolero", "kolizo",
  "kolo", "kolombo", "koloro", "kolumno", "kolumo", "kolorego", "komenci",
  "komerci", "kompleza", "kompreni", "komputi", "komputilo", "komuna", "komunismo",
  "konduki", "konduto", "konekto", "kongreso", "koni", "konkurso", "konsenti",
  "konsili", "konstruaĵo", "konstrui", "kontenta", "konto", "kontraŭ", "kontuzo",
  "konveni", "koralo", "korbopilko", "korespondi", "koro", "korpo", "korto",
  "korvo", "kosti", "kostizo", "kostumo", "koverto", "kovri", "kredebla", "kredi",
  "kreski", "kriaĉi", "krii", "kriketo", "krimo", "krimulo", "kristanismo",
  "kristano", "kritikisto", "krizo", "krokodilo", "krom", "kruda", "kruro",
  "kubuto", "kuirado", "kuirejo", "kuiri", "kukaburo", "kuketo", "kuko", "kulero",
  "kulpas", "kuneco", "kuniklo", "kupro", "kuraca", "kuracisto", "kuradi", "kuraĝa",
  "kuri", "kurso", "kuŝi", "kutime", "kutimiĝas", "kvankam", "kvazaŭ", "kverko",
  "laboratorio", "labori", "laboristo", "laca", "lacerto", "lago", "lakto", "lando",
  "lango", "langorompilo", "larĝa", "lasi", "lasta", "lavi", "leciono", "legi",
  "legomĝardeno", "legomo", "leono", "leontodo", "leporo", "lernejestro", "lernejo",
  "lerni", "letero", "levi", "libera", "libro", "ligi", "ligno", "ligo", "limigita",
  "limonado", "lingvisto", "lingvo", "linio", "lipo", "lito", "loĝi", "loko",
  "longa", "ludema", "ludi", "ludilo", "ludoj", "lumi", "lundo", "lunlumigita",
  "luno", "lupo", "majo", "makulo", "malatenti", "malegaleco", "maleolo",
  "malliberejo", "malriĉa", "malstreĉa", "malsupren", "malvarmumo", "mamulo",
  "manĝaĵo", "manĝo", "manki", "mano", "mantelo", "maralgo", "marbordo", "mardo",
  "margarito", "maristo", "marko", "markolo", "maro", "martelo", "marto",
  "matematikisto", "matenmanĝo", "mateno", "meblaro", "medicina", "mekanikisto",
  "meleagro", "membro", "memfido", "memori", "memorinda", "mensogulo", "merkredo",
  "metafore", "meteorologo", "meti", "mevo", "mezo", "mezuri", "migdalo",
  "miksaĵo", "militi", "ministro", "minuto", "miri", "misio", "mojosa", "momento",
  "monato", "mondo", "mono", "monto", "montri", "mirinda", "misiisto", "monujo",
  "morgaŭ", "morti", "mortigi", "mortigo", "mortpafi", "motorciklo", "movi",
  "multa", "muro", "muŝo", "muso", "nacio", "naĝi", "naski", "naskiĝi", "naturo",
  "nazo", "necesa", "necesejo", "nedankinde", "neĝo", "nekredebla", "nepino",
  "nepo", "neŭtrala", "nevino", "nevo", "nigra", "noktmezo", "nokto", "nombro",
  "nomo", "norda", "nova", "novaĵo", "novembro", "nuboj", "nulo", "obsedo",
  "oceano", "oceanografisto", "ofta", "okazi", "okcidento", "oktobro", "okulisto",
  "okulo", "okulvitroj", "okupi", "onklino", "onklo", "opinio", "oranĝkolora",
  "ordono", "orelo", "oriento", "orikteropo", "ornami", "ornitorinko", "oskedo",
  "paco", "pafi", "pafilo", "paleontologo", "pano", "pantoflo", "pantolono",
  "papago", "papero", "papilio", "paraŝuto", "pardoni", "parlamentano", "parolado",
  "parolema", "paroli", "parto", "pasero", "pasi", "paŝi", "pastro", "patrino",
  "patro", "peco", "peni", "pensi", "pentristo", "percepta", "percepto", "perdi",
  "permesi", "persono", "peti", "piedbati", "piedfingro", "piedmigradi", "piedo",
  "pilko", "pilolo", "pingvino", "pirato", "plaĉi", "plafono", "plaĝo", "planko",
  "plej", "plena", "plendi", "plenega", "plenkreskulo", "plenumi", "plezuro",
  "plori", "plumo", "pluvo", "pojno", "policestro", "policisto", "politikistino",
  "politikisto", "poluso", "polvo", "polvero", "pompa", "popolo", "pordo",
  "porkaĵo", "porko", "porti", "posedanto", "poŝo", "post", "posteno", "postuli",
  "potenca", "poto", "povi", "praavo", "pramo", "prauloj", "prava", "precioza",
  "precipa", "preĝejo", "premi", "premkaresi", "preni", "preskaŭ", "preta",
  "preter", "prezenti", "prezidanto", "prezidento", "printempo", "problemo",
  "profunda", "proksima", "promeni", "proponi", "propra", "prosperi", "provi",
  "psikologo", "pulmoj", "puni", "punkto", "pura", "purigi", "purpura", "racia",
  "radiko", "rajto", "rakonti", "rano", "rapida", "rato", "regi", "reĝido",
  "regilo", "reĝisoro", "registaro", "rekonstrui", "renkonti", "reno", "renoma",
  "reptilo", "resendi", "respondi", "resti", "resto", "restoracio", "resume",
  "retroviŝo", "retumi", "revado", "revemo", "riĉa", "ricevi", "riĉulo", "ridi",
  "rigardi", "rimarki", "rimedo", "rinocero", "ripozi", "rivero", "robo", "roko",
  "romanisto", "rompi", "rondo", "rondokule", "rozkolora", "rozo", "rubeno",
  "rubo", "rubriko", "rudimenta", "rufa", "ruĝa", "ruza", "sabato", "sablero",
  "sablo", "safiro", "ŝafo", "ŝafoj", "sago", "ŝajni", "salikoko", "salono",
  "salti", "saluti", "saluton", "sama", "sana", "sandalo", "sandviĉo", "ŝanĝi",
  "sango", "sardelo", "sarkasmo", "sata", "ŝati", "scientisto", "scii", "sciuro",
  "seĝo", "seka", "sekegeco", "sekretario", "sekretema", "sekundo", "sekvi",
  "semajnfino", "semajno", "sencela", "sendi", "sendube", "senkonscia",
  "senprecedenca", "senrekona", "senti", "sentima", "septembro", "serĉi",
  "serpento", "servi", "sidi", "sieĝo", "signo", "silenti", "simpla", "sinjoro",
  "ŝipestro", "ŝipo", "situacio", "skandalo", "skandi", "skatolo", "skribi",
  "skulptisto", "ŝlosi", "smeraldo", "sofo", "soifi", "sola", "soleno", "solvi",
  "somero", "sono", "sovaĝejo", "specimeno", "speco", "sperti", "spino",
  "ŝraŭbilo", "ŝraŭbo", "stacio", "ŝtalo", "stari", "stato", "statuo", "ŝteli",
  "stelo", "stevardo", "ŝtipo", "ŝtono", "strato", "strigo", "strio", "ŝtrumpetoj",
  "studento", "studi", "subtaso", "subvestoj", "suda", "suferi", "sufiĉe", "sukcesi",
  "sukero", "suko", "suno", "ŝuoj", "super", "supereco", "superforti", "supo",
  "supozi", "supro", "surda", "survoje", "suspektema", "ŝuti", "ŝvitado", "tablo",
  "tagmanĝo", "tagmezo", "tago", "tajdo", "tajpi", "taksiisto", "talaro", "tamen",
  "tapiŝo", "tasko", "taso", "taŭga", "taŭro", "teamo", "teatro", "tegmentoj",
  "teĥnika", "tekniko", "telero", "tempo", "teni", "tenilo", "teniso", "tero",
  "timi", "tineo", "tipo", "tiri", "tondi", "tondro", "tono", "traduki",
  "tradukisto", "trafi", "tramo", "tranĉi", "tranĉilo", "trankvila", "trans",
  "translokigi", "traŭmo", "trejnisto", "trejno", "trinkaĵo", "trinki", "trioble",
  "trista", "tritiko", "triumfo", "trivi", "trovi", "tulipo", "turmentita", "turni",
  "turto", "tuŝi", "tuta", "tutcerte", "ungo", "universo", "uragano", "urbestro",
  "urbo", "urso", "utila", "uzantoprofilo", "uzatas", "uzebla", "vagadi", "vagonaro",
  "vagono", "valizo", "valoro", "varbi", "varma", "varmega", "varmeta", "vartestino",
  "vasta", "veki", "velkanto", "vendejo", "vendi", "vendredo", "venĝe", "venĝo",
  "veni", "venta", "vento", "ventumilo", "vera", "verda", "verŝi", "vespermanĝo",
  "vespero", "vesperto", "vestaĵo", "vestiĝi", "vesto", "vetero", "veturi",
  "viando", "videbla", "vidi", "vidinda", "vidindaĵo", "viktimo", "vilaĝo", "vino",
  "vintro", "violkolora", "virino", "viro", "viruso", "viskio", "vitro", "vivi",
  "vizaĝo", "vizitadi", "viziti", "voĉo", "vojaĝi", "vojo", "voki", "volapukaĵo",
  "voli", "vombato", "vortaro", "vorto", "vortostoko", "vrako", "vulkano", "vulpo",
  "vundi", "vundo", "zammenhof", "zono", "zorgi"

];
