var vortListo = [

 "abelo", "abomeno", "abonanto", "abonas", "aboni", "abonis", "abono", "abonos",
 "abonu", "abonus", "aĉetado", "aĉetas", "aĉeti", "aĉetis", "aĉetos", "aĉetu",
 "aĉetus", "acida", "adiaŭ", "adicii", "adresaro", "adreso", "advokato", "aero",
 "aerodinamika", "aerostato", "afabla", "afero", "agado", "agas", "agento",
 "agis", "agitacio", "agitado", "agito", "aglo", "agmaniero", "agokula", "agordo",
 "agos", "agrabla",
 "agus", "ajlo", "akademio", "akceptado", "akceptas", "akcepti", "akceptis", "akceptos",
 "akceptu", "akceptus", "akcidento", "asekuro", "akiri", "akra", "akrido",
 "akso", "aktiva",
 "aktorino", "aktualigi", "akvo", "akvofalo", "alia", "alie", "aliflanke", "aligatoro",
 "aliĝi", "aliloke", "alimaniere", "alirebla", "alklaki", "allogi", "almenaŭ",
 "almozo",
 "alportis", "alpreni", "alŝuti", "alta", "altulo", "alumeto", "alveni", "amanto",
 "amara", "amas", "amasigi", "amaso", "ambaŭ", "ambaŭflanke", "ambulanco",
 "amikeco", "amikino", "amiko", "amikoj", "amis", "amos", "amus", "amuzanto",
 "amuzas", "amuzeco", "amuzi", "amuziĝis", "amuzis", "amuzos", "amuzu", "amuzus",
 "anaso", "angora", "angulo", "animo", "animstato", "ankaŭ", "ankoraŭ", "ankro",
 "anoncanto",
 "anoncas", "anonci", "anoncis", "anonco", "anoncos", "anoncu", "anoncus",
 "ansero", "anstataŭ", "anstataŭigas", "anstataŭigi", "anstataŭigis",
 "anstataŭigo", "anstataŭigos", "anstataŭigu", "anstataŭigus", "antaŭ",
 "antaŭprepara", "antaŭurbo", "antibakterio", "aparato", "aparta", "aparte",
 "apartenas", "aparteni", "apartenis", "apartenos", "apartenu", "apartenus",
 "apenaŭ", "aperas", "aperi", "aperis", "apero", "aperos", "aperu", "aperus",
 "apetito", "apoteko", "aprile", "aprilo", "apud", "arakido", "araneo", "aranĝas",
 "aranĝi", "aranĝis", "aranĝo", "aranĝos", "aranĝu", "aranĝus", "arbaro", "arbo",
 "arboj", "arbusto", "arego", "areto", "arĝenta", "arĝento", "arkitekto", "armilo",
 "aroganta", "artaĵo", "artefarita", "artgalerio", "artiklo", "artikolo",
 "artisto", "arto", "asocio", "aspektas", "aspekti", "aspektis", "aspekto",
 "aspektos", "aspektu", "aspektus", "astronomia", "astronomo", "atakanto",
 "atakas", "ataki", "atakis", "atako", "atakos", "ataku", "atakus", "ateismo",
 "atendado", "atendanto", "atendas", "atendi", "atendis", "atendos", "atendu",
 "atendus", "atenta", "atentas", "atenti", "atentinde", "atentis", "atento",
 "atentos", "atentu", "atentus", "atesto", "atingas", "atingi", "atingis",
 "atingo", "atingos", "atingu", "atingus", "aŭdas", "aŭdi", "aŭdis", "aŭdos",
 "aŭdu", "aŭdus", "aŭguro", "aŭguste", "aŭgusto", "aŭskultado", "aŭskultanto",
 "aŭskultas", "aŭskulti", "aŭskultis", "aŭskultos", "aŭskultu", "aŭskultus",
 "aŭto", "aŭtobuso", "aŭtomata", "aŭtomobilo", "aŭtono", "aŭtoritato", "aŭtune",
 "aŭtuno", "avara", "avelo", "aventuro", "averti", "aviadilo", "avino", "azeno",
 "bakterio", "balai", "baldaŭ", "baleno", "banas", "banĉambro", "bandaĝo", "bani",
 "banis", "bankisto", "banos", "banu", "banus", "baras", "barbo", "bari", "baris",
 "baro", "baros", "baru", "barus", "bastono", "batalanto", "batalas", "batali",
 "batalis", "batalo", "batalos", "batalu", "batalus", "batanto", "batas", "bati",
 "batis", "batita", "bato", "batos", "batu", "batus", "baze", "bazo", "bebo",
 "bedaŭras", "bedaŭri", "bedaŭris", "bedaŭro", "bedaŭros", "bedaŭru", "bedaŭrus",
 "bela", "beleco", "belulino", "belulo", "benko", "beno", "benzinujo", "besto",
 "bestoĝardeno", "bezonas", "bezonata", "bezoni", "bezonis", "bezono", "bezonos", "bezonu",
 "bezonus", "bibliotekisto", "biblioteko", "biciklanto", "biciklas", "bicikli",
 "biciklis", "biciklisto", "biciklo", "biciklos", "biciklu", "biciklus", "biero",
 "bildo", "bileto", "biokemiisto", "biologo", "birdaro", "birdido", "birdo",
 "blanka", "blasfemi", "blinda", "blonda", "blovas", "blovi", "blovis", "blovos",
 "blovu", "blovus", "blua", "boato", "bofratino", "bofrato", "bogepatroj", "boji",
 "bolado", "bolas", "boli", "bolis", "bolos", "bolu", "bolus", "bombono", "bona",
 "boneco", "bonega", "bonege", "bonfarasocieto", "bonŝance", "bopatrino",
 "bopatro", "bordo",
 "botanikisto", "botelo", "bovaĵo", "bovino", "bovlo", "bovo", "bradipo",
 "brakhorloĝo", "brako", "brakumas", "brakumi", "brakumis", "brakumos", "brakumu",
 "brakumus", "branĉo", "brando", "breto", "brilas", "brili", "brilis", "brilos",
 "brilu", "brilus", "bronza", "broso", "bruas", "brui", "bruis", "brulas", "bruli",
 "bruliĝi", "brulis", "brulos", "brulu", "brulus", "bruna", "bruo", "bruos",
 "brusto", "bruteca", "bruu", "bruus", "bubo", "buĉi", "bushaltejo", "buso",
 "buŝo", "butero", "butiko", "butikumi", "butono", "butonumi", "ĉagrenita",
 "ĉagreno", "ĉambro", "ĉambroj", "ĉanto", "ĉapelo", "ĉarmita", "ĉasi", "ĉefa",
 "ĉefaj", "ĉefministro", "ĉefo", "ĉefoj", "ĉefurbo", "celado", "celi", "celo",
 "ĉemizo",
 "ĉemizoj", "cent", "centono", "centro", "cepo", "cerbo", "cerbumi", "ĉerizo",
 "certa", "certeco", "certigi", "certigo", "cervo", "ĉesanto", "ĉesas", "ĉesi",
 "ĉesigi",
 "ĉesis", "ĉesos", "ĉesu", "ĉesus", "cetera", "ceteraj", "cetero", "ĉevalo",
 "ĉiam", "ĉian", "cidro", "ĉielo", "ĉielkorpo", "ĉien", "cigaredo", "cigno",
 "cikatro", "ĉion",
 "ĉirkaŭ", "ĉirkaŭrigadi", "cirklo", "cirkloj", "cirko", "ĉisi", "ĉiuj",
 "ĉiujara",
 "ĉiujn", "ĉiun", "civilizo", "ĉokolado", "cunamo", "ĉusigno", "dancado",
 "dancanto", "dancas", "danci", "dancis", "dancistino", "dancisto", "danco",
 "dancos", "dancu", "dancus", "danĝera", "danĝero", "dankas", "danke", "dankema",
 "danki", "dankis", "dankon", "dankos", "danku", "dankus", "daŭras", "daŭre",
 "daŭri", "daŭris", "daŭro", "daŭros", "daŭru", "daŭrus", "dece", "decembre",
 "decembro", "decidas", "decidi", "decidis", "decidita", "decido", "decidos",
 "decidu",
 "decidus", "dedukto", "defendanto", "defendas", "defendi", "defendis",
 "defendos",
 "defendu", "defendus", "defio", "degeli", "deiro", "dekstra", "dekstre",
 "dekstren",
 "delogaĵo", "demandanto", "demandas", "demandi", "demandis", "demando",
 "demandos", "demandu", "demandus", "denove", "densa", "dentbroso", "dentisto",
 "dento", "dentoj", "depost", "deprenas", "deprenis", "deprenos", "desegnaĵo",
 "desegnanto", "desegnas", "desegni",
 "desegnis", "desegnisto", "desegnos", "desegnu", "desegnus", "detala", "detale",
 "detalo", "devas", "devi", "devigi", "devis", "devo", "devos", "devu", "devus",
 "deziranto", "deziras", "deziri", "deziris", "deziro", "deziros", "deziru",
 "dezirus", "diamanto", "dianto", "diferencas", "diferenci", "diferencis",
 "diferenco", "diferencos", "diferencu", "diferencus", "difinas", "difini",
 "difinis", "difino", "difinos", "difinu", "difinus", "dika", "dimanĉe",
 "dimanĉo",
 "dioj", "diplomo", "diraĵo", "diranto", "diras", "direktado", "direkti",
 "direkto", "direktoro", "diri", "diris", "diros", "diru", "dirus", "disfalas", "disfalis", "disfalos", 
 "disĵeti", "disko", "diskreta", "diskutanto", "diskutas", "diskuti", "diskutis",
 "diskuto", "diskutos", "diskutu", "diskutus", "disponebla", "dissendi",
 "disŝiras", "disŝiri", "disŝiris", "disŝiros", "disŝiru", "disŝirus",
 "disvolvado", "diveni", "diversa", "diverseco", "dividas", "dividi", "dividis",
 "divido", "dividos", "dividu", "dividus", "doganisto", "doktoro", "dolĉa",
 "dolĉe", "doloras", "dolori", "doloris", "doloro", "doloros", "doloru", "dolorus",
 "domaĉo", "domaĝe", "domaĝo", "domanaro", "dombesto", "domego", "dometo",
 "domo", "donacas", "donaci", "donacis", "donaco", "donacos", "donacu",
 "donacus", "donado", "donanto", "donas", "doni", "donis", "donos", "donu",
 "donus",
 "dormanto", "dormas", "dormĉambro", "dormema", "dormi", "dormis", "dormo",
 "dormos", "dormu", "dormus", "dorse", "dorso", "drato", "dresi", "drinkejo",
 "dubanto", "dubas", "dubi", "dubis", "dubo", "dubos", "dubu", "dubus", "dulingva", "dunganto",
 "dungas", "dungi", "dungis", "dungos", "dungu", "dungus", "duno", "duobla",
 "duoblo", "duona", "ebena", "ebligas", "ebligis", "ebligos", "ebligus", "edukado", 
  "edukas", "eduki", "edukis", "edukos",
 "eduku", "edukus", "edziĝi", "edziniĝi", "edzino", "edzo", "efektiva", "efektive",
 "efikas", "efike", "efiki", "efikis", "efiko", "efikos", "efiku", "efikus",
 "egala", "ekbrili", "ekkoncio", "ekkrias", "ekkrii", "ekkriis", "ekkrios",
 "ekkriu", "ekkrius", "ekonomikisto", "ekonomio", "ekrano", "ekrigardi", "ekscita",
 "eksciti", "ekscito", "ekskremento", "ekskurso", "eksperimenta", "ekspozicio",
 "ekster", "eksterterano", "eksterteranoj", "ekzamenas", "ekzameni", "ekzamenis",
 "ekzameno", "ekzamenos", "ekzamenu", "ekzamenus", "ekzemplo", "ekzemploj",
 "ekzercado", "ekzercas", "ekzerci", "ekzercis", "ekzerco", "ekzercos", "ekzercu",
 "ekzercus", "ekzistanto", "ekzistas", "ekzisti", "ekzistis", "ekzisto", "ekzistos",
 "ekzistu", "ekzistus", "eldonisto", "elefanto", "elektado", "elektanto", "elektas",
 "elekti", "elektis", "elekto", "elektos", "elektro", "elektu", "elektus",
 "elemento",
 "elkore", "elserĉi", "elspezo", "elspiri", "elŝuti", "elteni", "eluzi",
 "emocie", "emocio",
 "energie", "energio", "enigmo", "enspezo", "enspiri", "enterigita", "entrepeni",
 "entreprenisto", "entrudinto", "entuziasmo", "enui", "enviinda", "epidemio",
 "episkopino", "eraras", "erari", "eraris", "eraro", "eraros", "eraru", "erarus",
 "erupcio", "escepta", "esperanto", "esperas", "esperi", "esperis", "espero",
 "esperos",
 "esperu", "esperus", "esplorado", "esploras", "esplori", "esploris", "esploristo",
 "esploro", "esploros", "esploru", "esplorus", "esprimas", "esprimi", "esprimis",
 "esprimo", "esprimos", "esprimu", "esprimus", "estaĵo", "estanteco", "estas",
 "esti", "estimas", "estimi", "estimis", "estimo", "estimos", "estimu", "estimus",
 "estinteco", "estis", "estonteco", "estos", "estu", "estus", "etaĝo", "etendi",
 "etika", "etikedo", "etna", "etnografo", "etoso", "etspirita", "eventuala", "eventuale",
 "evoluado", "evoluas", "evolui", "evoluis", "evoluos", "evoluu", "evoluus",
 "facila", "facile", "fadeno", "fajfi", "fajrero", "fajro", "fako", "fakte", "fakto",
 "fakturo", "fakulo", "falanto", "falas", "faldi", "faleto", "fali", "falis",
 "falko", "falo", "falos", "falu", "falus", "fama", "familiano", "familianoj",
 "familiara", "familio", "familioj", "famo", "famulo", "fantazio", "farado",
 "faranto", "faras", "fari", "faris", "faros", "fartas", "farti", "fartis",
 "fartos", "fartu", "fartus", "faru", "farus", "fascina", "fasmo", "fatraso",
 "februare",
 "februaro", "feino", "feliĉa", "feliĉe", "fendi", "fenestro", "fenestroj",
 "ferio", "ferioj", "fermas", "fermi", "fermis", "fermita", "fermos", "fermu",
 "fermus", "fero", "fervojo", "fervorulo", "festanto", "festas", "festi", "festis",
 "festivalo", "festo", "festos", "festu", "festus", "fianĉo", "fiero", "fifama",
 "fiksas", "fiksi", "fiksis", "fiksos", "fiksu", "fiksus", "filino", "filmo",
 "filo", "filozofo", "finas", "finfine", "fingro", "fingroj", "fingropremaĵo",
 "fina", "fini",
 "finis", "fino", "finos", "finu", "finus", "firme", "fiŝaĵo", "fiŝkaptisto",
 "fiŝo", "fiŝoj", "fizikisto", "fiziologo", "flago", "flamo", "flanke", "flanko",
 "flari", "flava", "flegistino", "flirtumi", "floraro", "flori", "floristo",
 "floro", "floroj", "flua", "fluas", "fluganto", "flugas", "flughaveno", "flugi",
 "flugiloj", "flugis", "flugos", "flugu", "flugus", "flui", "fluis", "fluo",
 "fluos", "flustri", "fluu", "fluus", "foje", "fojo", "foko", "folio", "folioj",
 "fondas", "fondi", "fondinto", "fondis", "fondos", "fondu", "fondus", "fondusoj",
 "fonto", "fontoj", "foresto", "forgesanto", "forgesas", "forgeseco", "forgesema",
 "forgesi", "forgesis", "forgesita", "forgesos", "forgesu", "forgesus", "forkapti",
 "forko", "forkoj", "formo", "formorti", "forpreni", "forpuŝi", "forta", "forteco",
 "fortulo", "fosanto", "fosas", "fosi", "fosis", "fosisto", "fosos", "fosu",
 "fosus",
 "fotanto", "fotas", "fotato", "foti", "fotilo", "fotinda", "fotis", "fotistino",
 "fotisto", "fotito", "foto", "fotos", "fototo", "fotu", "fotus", "frapanto",
 "frapas", "frapeto", "frapi", "frapis", "frapo", "frapos", "frapu", "frapus",
 "fratino", "frato", "fraŭlino", "fraŭlo", "frazo", "frekventi", "fremda",
 "fremdeco", "fremdulo", "freneza", "frenezeco", "frenezulo", "freŝa", "fridujo",
 "fripono", "friti", "fritita", "frizisto", "fromaĝo", "frostiĝas", "frostiĝi",
 "frostiĝis",
 "frostiĝos", "frostiĝu", "frostiĝus", "frosto", "frua", "frue", "frukto",
 "frunto", "fuĝi", "fulmo", "fulmotondro", "fumanto", "fumo", "fungoj", "funkcias",
 "funkcii", "funkciis", "funkcio", "funkcios", "funkciu", "funkcius", "fuŝado",
 "fuŝanto", "fuŝas", "fuŝi", "fuŝis", "fuŝo", "fuŝos", "fuŝu", "fuŝus", "futbalo",
 "gaja", "gajnanto", "gajnas", "gajni", "gajninto", "gajnis", "gajno", "gajnos",
 "gajnu", "gajnus", "ĝangalo", "ĝardenisto", "ĝardeno", "gaso", "gastas", "gasti",
 "gastigas", "gastigi", "gastigis", "gastigos", "gastigu", "gastigus", "gastis",
 "gasto", "gastos", "gastu", "gastus", "gazeto", "geamikoj", "geavoj", "geedzeco",
 "geedzoj", "gefiloj", "gefratoj", "gefraŭloj", "geknaboj", "gekuzoj", "ĝemi",
 "ĝemspiro", "ĝenanto", "ĝenas", "genepoj", "ĝenerala", "genevoj", "ĝeni", "ĝenis",
 "ĝeno", "ĝenos", "ĝentila", "ĝentileco", "ĝenu", "genuo", "ĝenus", "geografio",
 "geografo", "gepatroj", "gesinjoroj", "ginekologo", "ĝisdatigi", "glaciaĵo",
 "glacio", "glano", "glaso", "glavingo", "glisaviadilo", "glitanto", "glitas",
 "gliti", "glitilo", "glitis", "glitos", "glitu", "glitus", "globo", "ĝoja",
 "ĝojanto", "ĝojas", "ĝoji", "ĝojis", "ĝojo", "ĝojos", "ĝoju", "ĝojus", "golo",
 "grafikisto", "granda", "grandeco", "grasa", "graso", "gratulanto", "gratulas",
 "gratuli", "gratulis", "gratulon", "gratulos", "gratulu", "gratulus", "grava",
 "gravas", "gravi", "gravis", "gravos", "gravulo", "gravus", "greno", "grilo",
 "grimpi", "griza", "grupo", "ĝuado", "ĝuanto", "ĝuas", "ĝuebla", "ĝuis", "gumo",
 "ĝuos", "ĝusta", "ĝuste", "gusto", "gustumas", "gustumi", "gustumis", "gustumos",
 "gustumu", "gustumus", "ĝuus", "gvidado", "gvidanto", "gvidas", "gvidi", "gvidis",
 "gvidisto", "gvidos", "gvidu", "gvidus", "hajlo", "haki", "hakilo", "haltas",
 "halti",
 "haltis", "halto", "haltos", "haltu", "haltus", "ĥaoso", "hararo", "haro",
 "haroj", "haŭto", "havas", "havebla", "haveno", "havi", "havis", "havos", "havu",
 "havus", "hazarda", "hejme", "hejmen", "hejmo", "hejmtasko", "hejtilo", "hela",
 "heliko", "helikoptero", "helpanto", "helpas", "helpema", "helpi", "helpis",
 "helpo", "helpos", "helpu", "helpus", "ĥemio", "hepato", "herbo", "heroo",
 "hidrologo", "hieraŭ", "heredaĵo", "ĥimero", "hipopotamo", "hirundo", "histerio", "historia",
 "historiisto", "historio", "hodiaŭ", "ĥolera", "homamaso", "homaro", "homo",
 "homoj", "horaro", "hore", "horloĝo", "horo", "ĥoro", "horoj", "hotelestro",
 "hotelo", "humila", "humuro", "hundeco", "hundido", "hundino", "hundo",
 "hundokaptisto",
 "huraado", "idealo", "ideo", "iĝadas", "iĝadi", "igvano", "imagas", "imagi", "imagis", 
  "imago", "imagos", "imagu", "imagus", "imitanto", "imitas", "imiti", "imitis", 
  "imito", "imitos", "imitu", "imitus", "implicas", "implice", "implici", "implico", 
  "implicoj", "implikacio", "implikanta", "implikaĵo", "impliki", "implikiĝi", 
  "implikiĝo", "improvizu", "industrio", "infano", "infanoj", "informas",
 "informi", "informis", "informo", "informos", "informu", "informus", "inĝeniero",
 "iniciati",
 "iniciativo", "injekto", "inkvizicio", "insekto", "insigno", "insolenta",
 "instruado", "instruas", "instrui", "instruis", "instruistino", "instruisto",
 "instruos", "instruu", "instruus", "insulo", "inteligenta", "inteligenteco",
 "intencas", "intence", "intenci", "intencis", "intenco", "intencos", "intencu",
 "intencus", "inter", "interalie", "interesa", "interesanto", "interesas", "interesi",
 "interesiĝas", "interesiĝi", "interesiĝis", "interesiĝos", "interesiĝus",
 "interesis", "interesos", "interesu", "interesus", "interna", "internacia",
 "interno", "interreto", "interrompi", "inundo", "inventisto", "invitanto",
 "invitas", "inviti", "invitis", "invitito", "invito", "invitos", "invitu",
 "invitus", "iranto", "iras", "iris", "ironia", "ironio", "iros", "irus", "iufoje",
 "jaĥto", "jako", "ĵaluza", "januare", "januaro", "jare", "jaro", "ĵaŭde", "ĵaŭdo",
 "ĵetanto", "ĵetas", "ĵeti", "ĵetis", "ĵeto", "ĵetos", "ĵetu", "ĵetus", "juĝanto",
 "juĝas", "juĝi", "juĝis", "juĝisto", "juglando", "juĝos", "juĝu", "juĝus", "julie",
 "julio", "juna", "juneco", "junie", "junio", "junulo", "jupo", "ĵuri", "juristo",
 "ĵurnalo", "justa", "justeco", "juvelisto", "kablo", "kadro", "kafejo", "kafo",
 "kajero", "kajo", "kalendaro", "kalkulado", "kalkulas", "kalkuli", "kalkulis",
 "kalkulo", "kalkulos", "kalkulu", "kalkulus", "kamelo", "kameno", "kamioneto",
 "kamiono", "kamparo", "kampo", "kanario", "kandelingo", "kanguruo", "kanjono",
 "kantado", "kantaro", "kantas", "kanti", "kantis", "kantistino", "kantisto",
 "kanto", "kantos", "kantu", "kantus", "kanuo", "kapabla", "kapableco", "kapjesas",
 "kapjesi", "kapjesis", "kapjesos", "kapo", "kapro", "kaptanto", "kaptas", "kapti",
 "kaptis", "kaptita", "kaptos", "kaptu", "kaptus", "kara", "karbo", "karmparano",
 "kartaro", "kartludo", "karto", "kartografo", "karulino", "karulo", "kaŝanto",
 "kaŝas",
 "kasedo", "kaŝi", "kaŝis", "kaso", "kaŝos", "kastelo", "kaŝu", "kaŝus",
 "katastrofo", "katido", "kato", "kaŭĉuko", "kaŭzo", "kazo", "kazoj", "kelka",
 "kelkaj", "kelnerino", "kemiisto", "kerno", "kesto", "kiaj", "kiajn", "kial",
 "kiam", "kian", "kiel", "kien", "kies", "kilogramo", "kilometro", "kiom", "kion",
 "kirurgio", "kisas", "kisi", "kisis", "kiso", "kisos", "kisu", "kisus", "kiuj",
 "kiujn", "klaki", "klara", "klarigas", "klarigi", "klarigis", "klarigos",
 "klarigu", "klarigus", "klaso", "klaŭno", "klera", "klimatizado", "klimato",
 "klinas", "klingo", "klini", "kliniigi", "klinis", "klino", "klinos", "klinu",
 "klinus", "kliŝo", "klopodanto", "klopodas", "klopodi", "klopodis", "klopodo",
 "klopodos",
 "klopodu", "klopodus", "klubano", "klubo", "knabaĝo", "knabino", "knabo",
 "kokcinelo", "kokinaĵo", "kokino", "kokoso", "kolektanto", "kolektas", "kolekti",
 "kolektis", "kolekto", "kolektos", "kolektu", "kolektus", "koleras", "koleri",
 "koleriĝas", "koleriĝi", "koleriĝis", "koleriĝos", "koleriĝu", "koleriĝus",
 "koleris", "kolero", "koleros", "koleru", "kolerus", "kolizio", "kolo", 
  "kolombo", "koloniistoj", 
 "kolorego", "kolorigas", "kolorigi", "kolorigis", "kolorigos", "kolorigu",
 "kolorigus", "koloro", "koloroj", "koltuko", "kolumno", "kolumo", "kombas",
 "kombi", "kombilo", "kombis", "kombos", "kombu", "kombus", "komencanto",
 "komencas", "komenci", "komenciĝas", "komenciĝi", "komenciĝis", "komenciĝos",
 "komenciĝu", "komenciĝus", "komencis", "komenco", "komencos", "komencu",
 "komencus", "komercas", "komerci", "komercis", "komercisto", "komerco",
 "komercos", "komercu", "komercus", "komforta", "komfortaj", "komforto",
 "komisias", "komisii", "komisiis", "komisiito", "komisio", "komisios", "komisiu",
 "komisius", "komitato", "komparanto", "komparas", "kompari", "komparis",
 "komparo", "komparos", "komparu", "komparus", "kompatanto", "kompatas", "kompati",
 "kompatis", "kompato", "kompatos", "kompatu", "kompatus", "kompleza", "komplika",
 "komplimento", "komprenado", "komprenanto", "komprenas", "kompreni", "komprenis",
 "komprenos", "komprenu", "komprenus", "komputas", "komputi", "komputilo",
 "komputis",
 "komputisto", "komputos", "komputu", "komputus", "komuna", "komunikado",
 "komunikanto", "komunikas", "komuniki", "komunikis", "komunikos", "komuniku",
 "komunikus", "komunismo", "konas", "koncernanto", "koncernas", "koncerni",
 "koncernis", "koncerno", "koncernos", "koncernu", "koncernus", "kondiĉe",
 "kondiĉo", "kondukanto", "kondukas", "konduki", "kondukis", "konduko", "kondukos",
 "konduku", "kondukus", "konduti", "konduto", "konekto", "konfesanto", "konfesas",
 "konfesi", "konfesis", "konfeso", "konfesos", "konfesu", "konfesus", "konformiĝi", 
  "konformiĝo", 
 "kongresantoj", "kongresejo", "kongreso", "kongresumi", "koni", "konis", "konko",
 "konkreta", "konkreto", "konkurso", "konos", "konsentanto", "konsentas",
 "konsenti", "konsentis", "konsentite", "konsento", "konsentos", "konsentu",
 "konsentus", "konservanto", "konservas", "konservi", "konservis", "konservos",
 "konservu", "konservus", "konsideranto", "konsideras", "konsideri", "konsideris",
 "konsidero", "konsideros", "konsideru", "konsiderus", "konsilanto", "konsilas",
 "konsili", "konsilis", "konsilisto", "konsilo", "konsilos", "konsilu", "konsilus",
 "konsistanto", "konsistas", "konsisti", "konsistis", "konsistos", "konsistu",
 "konsistus", "konstanta", "konstitutcia", "konstitucie", "konstitucio", "konstruaĵo", 
  "konstruanto", "konstruas", "konstrui",
 "konstruis", "konstruisto", "konstruos", "konstruu", "konstruus", "kontakto",
 "kontenta", "konto", "kontraŭ", "kontraŭas", "kontraŭi", "kontraŭis", "kontraŭos", "kontraŭpezo", 
 "kontraŭstari", "kontraŭu", "kontraŭus", "kontrolanto", "kontrolas", "kontroli",
 "kontrolis", "kontrolo", "kontrolos", "kontrolu", "kontrolus", "kontuzo", "konu",
 "konus", "konvenanto", "konvenas", "konveni", "konvenis", "konveno", "konvenos",
 "konvenu", "konvenus", "konvinkanto", "konvinkas", "konvinki", "konvinkis",
 "konvinkos", "konvinku", "konvinkus", "kopianto", "kopias", "kopii", "kopiis",
 "kopio", "kopios", "kopiu", "kopius", "koralo", "korbo", "korbopilko",
 "korespondanto", "korespondas", "korespondi", "korespondis", "korespondos",
 "korespondu", "korespondus", "koro", "korpo", "korto", "korvo", "kostas", "kosti",
 "kostis", "kostizo", "kosto", "kostos", "kostu", "kostumo", "kostus", "koverto",
 "kovranto", "kovras", "kovri", "kovris", "kovros", "kovru", "kovrus", "krajono",
 "krampfi", "krampfo", "krano", "kreanto", "kreas", "kredanto", "kredas", "kredebla",
 "kredi", "kredis",
 "kredo", "kredos", "kredu", "kredus", "krei", "kreis", "kreos", "kreskanto",
 "kreskas", "kreski", "kreskis", "kreskos", "kresku", "kreskus", "kreto", "kreu",
 "kreus", "kriaĉi", "krianto", "krias", "krii", "kriis", "kriketo", "krimo",
 "krimulo", "krio", "krios", "kristanismo", "kristano", "kritikisto", "kriu",
 "krius", "krizo", "krokodilo", "krom", "kruda", "kruela", "kruro", "kubuto",
 "kudranto", "kudras", "kudri", "kudris", "kudros", "kudru", "kudrus", "kuirado",
 "kuiranto", "kuiras", "kuirejo", "kuiri", "kuiris", "kuiristo", "kuiros", "kuiru",
 "kuirus", "kukaburo", "kuketo", "kuko", "kukolo", "kulero", "kulo", "kulpa",
 "kulpas", "kultivi", "kulturanto", "kulturas", "kulturi", "kulturis", "kulturo",
 "kulturos", "kulturu", "kulturus", "kundividas", "kundividi", "kundividis",
 "kundividos", "kundividu", "kundividus", "kuneco", "kuniklo", "kunlaboro", "kunportas",
 "kunporti", "kunportis", "kunportos", "kunportu", "kunportus", "kunteniĝa",
 "kunvivanto", "kupono", "kupro", "kuraca", "kuracas", "kuraci", "kuracis",
 "kuracisto", "kuracos", "kuracu", "kuracus", "kuradi", "kuraĝa", "kuranto",
 "kuras", "kure", "kuri", "kuris", "kuros", "kurso", "kurteno", "kuru", "kurus",
 "kuŝanto", "kuŝas", "kuŝi", "kuŝis", "kuŝos", "kuŝu", "kuŝus", "kutimanto",
 "kutimas", "kutime", "kutimi", "kutimiĝas", "kutimis", "kutimos", "kutimu",
 "kutimus", "kuzino", "kuzo", "kvadrato", "kvalito", "kvankam", "kvanto", "kvar",
 "kvartalo", "kvazaŭ", "kverko", "kvin", "laboranto", "laboras", "laboratorio",
 "laborejo", "labori", "laboris", "laboristo", "laboro", "laboros", "laboru",
 "laborus", "laca", "laceco", "lacega", "lacerto", "lago", "laktejo", "lakto",
 "lanĉi",
 "lando", "lango", "langorompilo", "larĝa", "lasanto", "lasas", "lasi", "lasis",
 "lasos", "lasta", "lastatempe", "laste", "lasu", "lasus", "laŭplaĉe", "laŭŝajne",
 "laŭta", "lavado", "lavanto", "lavas", "lavi", "lavis", "lavmaŝino", "lavos",
 "lavu", "lavus", "leciono", "legado", "leganto", "legas", "legi", "legis",
 "leĝisto", "leĝo", "legomĝardeno", "legomo", "legomoj", "legos", "legu", "legus",
 "leono", "leontodo", "leporo", "lernado", "lernanto", "lernas", "lernejestro",
 "lernejo", "lerni", "lernis", "lernos", "lernu", "lernus", "lerta", "lerteco",
 "lertulo", "letero", "leteroj", "levanto", "levas", "levi", "levis", "levos",
 "levu", "levus", "libera", "libereco", "liberigas", "liberigi", "liberigis",
 "liberigos", "liberigu", "liberigus", "libro", "liganto", "ligas", "ligi",
 "ligis", "lignero", "lignisto", "ligno", "ligo", "ligos", "ligu", "ligus",
 "limako", "limigita", "limo", "limonado", "lingvisto", "lingvo", "linio",
 "linioj", "lipo", "lipoj", "listo", "litĉambro", "literaturo", "litero",
 "literoj", "litkovrilo", "lito", "loĝado", "loĝanto", "loĝas", "loĝi", "loĝis",
 "loĝos", "loĝu", "loĝus", "loka", "lokaj", "loko", "longa", "longe", "longeco",
 "ludanto", "ludas", "ludema", "ludi", "ludilo", "ludis", "ludo", "ludoj",
 "ludos", "ludu", "ludus", "lumi", "lumo", "lunde", "lundo", "lunlumigita",
 "lunlumo", "luno", "lupo",
 "maĉi", "maje", "majo", "majstro", "maki", "makulo", "malaktuala", "malaperas",
 "malaperi", "malaperinta", 
 "malaperis", "malapero", "malaperos", "malaperu", "malaperus", "malatenti",
 "malbona", "maldekstra", "maldekstre", "maldekstren", "maldika", "malegaleco",
 "maleolo",
 "malfacila", "malfacile", "malfeliĉa", "malfeliĉe", "malfermas", "malfermi",
 "malfermis", "malfermita", "malfermos", "malfermu", "malfermus", "malforta", 
  "malfortis", "malforto", "malfortos", "malfreŝa",
 "malĝentila", "malgranda", "malgraŭ", "malhela", "malica", "maljuna", "maljuneco",
 "maljunulo", "maljusta", "malkaŝiĝi", "malkaŝu", "malliberejo", "malmoderna",
 "malmola", "malordo", "malpliigo", "malriĉa", "malsaĝa", "malsaĝulo", "malsana",
 "malsanulejo", "malsanulo", "malsata", "malseka", "malsekiĝas", "malsekiĝi",
 "malsekiĝis", "malsekiĝos", "malsekiĝus", "malserioza", "malsimila", "malsimpla",
 "malstreĉa", "malstreĉiĝas", "malstreĉiĝi", "malstreĉiĝis", "malstreĉiĝos",
 "malstreĉiĝus", "malsupre", "malsupren", "malvarma", "malvarme", "malvarmiĝas",
 "malvarmiĝi", "malvarmiĝis", "malvarmiĝos", "malvarmiĝus", "malvarmumo",
 "malvera", "malvigla", "mamo", "mamulo", "mane", "manĝaĵo", "manĝanto", "manĝas",
 "manĝejo", "manĝi", "manĝilaro", "manĝis", "manĝo", "manĝos", "manĝu", "manĝus",
 "maniero", "mankanto", "mankas", "manki", "mankis", "manko", "mankos", "manku",
 "mankus", "mano", "manoj", "mansako", "mantelo", "maralgo", "marbordo", "marde",
 "mardo", "margarito", "maristo", "marko", "markolo", "marmanĝaĵo", "maro",
 "marŝanto", "marŝas", "marŝi", "marŝis", "marŝo", "marŝos", "marŝu", "marŝus",
 "marte", "martelo", "marto", "marvirino", "maŝino", "mastro", "matematikisto",
 "matene", "matenmanĝo", "mateno", "materialo", "meblaro", "meblo", "mebro",
 "medicina", "medio", "mekanikisto", "meleagro", "membro", "memfido", "memmortigi",
 "memori", "memorigas", "memorigi", "memorigis", "memorigos", "memorigu",
 "memorigus", "memorinda", "memoro", "mendanto", "mendas", "mendi", "mendis",
 "mendo", "mendos", "mendu", "mendus", "menso", "mensogi", "mensogulo", "mensoj",
 "mentono", "meritanto", "meritas", "meriti", "meritis", "merito", "meritos",
 "meritu", "meritus", "merkrede", "merkredo", "metado", "metafore", "metalo",
 "metanto", "metas", "meteorologo", "meti", "metis", "metodo", "metos", "metro",
 "metu", "metus", "mevo", "mezo", "mezuranto", "mezuras", "mezuri", "mezuris",
 "mezuro", "mezuros", "mezuru", "mezurus", "miaŭi", "migdalo", "miksaĵo",
 "miksanto", "miksas", "miksi", "miksis", "mikso", "miksos", "miksu", "miksus",
 "miliono", "militanto", "militas", "militi", "militis", "militisto", "militos",
 "militu", "militus", "miljaro", "ministro", "minus", "minuto", "minutoj",
 "miranto", "miras", "miri", "mirige", "mirinda", "mirinde", "miris", "miros",
 "miru", "mirus", "misiisto", "misio", "misĵetas", "misĵeti", "misĵetis",
 "misĵetos", "mistrafis", "modera", "moderna", "modifiki", "modo", "mojosa",
 "mokanto",
 "mokas", "moki", "mokis", "moko", "mokos", "moku", "mokus", "mola", "momento",
 "momentoj", "monate", "monato", "monatoj", "monbileto", "mondo", "monero",
 "mono",
 "montaro", "monto", "montoj", "montranto", "montras", "montri", "montris",
 "montros", "montru", "montrus", "monujo", "mordeti", "mordi", "morgaŭ",
 "mortanto", "mortas", "morti", "mortigas", "mortigi", "mortigis", "mortigo",
 "mortigos", "mortigulo", "mortigus", "mortis", "morto", "mortos", "mortpafi",
 "mortu", "mortus", "motorciklo", "movanto", "movas", "movi", "moviĝas", "moviĝi",
 "moviĝis", "moviĝos", "moviĝu", "moviĝus", "movis", "movo", "movos", "movu",
 "movus", "multa", "multe", "multfoje", "multlingva", "municipe", "muntaĵo", "munti", "muro",
 "muskolo", "muso", "muŝo", "muzeo", "muzikisto", "muziko", "nacia", "nacio", "naĝado",
 "naĝanto", "naĝas", "naĝejo", "naĝi", "naĝis", "naĝisto", "naĝos", "naĝu",
 "naĝus", "najbaro", "najbaroj", "narcisismo", "naskanto", "naskas", "naski",
 "naskiĝas",
 "naskiĝdatreveno", "naskiĝi", "naskiĝis", "naskiĝos", "naskiĝus", "naskis",
 "nasko", "naskos", "nasku", "naskus", "naturo", "naŭza", "naŭzo", "nazo",
 "nazringo", "nebulo", "necesa", "necesejo", "neceso", "nedankinde", "neĝas",
 "neĝe", "neĝero", "neĝi", "neĝis", "neĝo", "neĝos", "neĝu", "neĝus", "neĝviro",
 "nejusta", "nekredebla", "nekredeble", "nenia", "neniam", "nenie", "neniel",
 "nenifarado", "neniigo", "nenio", "neniom", "nenombrebla", "nenormala",
 "nepino", "nepo", "nepre", "nesekura", "neŭtrala", "nevino", "nevo", "nigra",
 "nigreco",
 "nivelo", "niveloj", "noktmezo", "nokto", "noktoj", "nomas", "nomata", "nombro", "nomi",
 "nomiĝas", "nomiĝi", "nomis", "nomo", "nomos", "nomu", "nomus", "norda",
 "norden", "nordo", "normala", "normale", "notanto", "notas", "noti", "notis",
 "noto", "notos", "notu", "notus", "nova", "novaĵo", "novembro", "novigado",
 "novulo", "nubo", "nuboj", "nukso", "nulo", "numero", "obeanto", "obeas",
 "obei", "obeis", "obeos", "obeu", "obeus", "objeckto", "objekto", "obsedo",
 "oceano", "oceanografisto", "odoranto", "odoras", "odori", "odoris", "odoro",
 "odoros", "odoru", "odorus", "oficejo",
 "ofico", "ofta", "ofte", "ofteco", "okazanto", "okazas", "okaze", "okazi",
 "okazis", "okazos", "okazu", "okazus", "okcidenten", "okcidento", "oktobro",
 "okulisto", "okulo", "okuloj", "okulvitroj", "okupanto", "okupas", "okupata",
 "okupi", "okupis", "okupita", "okupos", "okupu", "okupus", "oleo", "ombrelo",
 "ombro", "onidiro", "onklino", "onklo", "opinii", "opinio", "oranĝkolora",
 "ordinara", "ordinare", "ordo", "ordonanto", "ordonas", "ordoni", "ordonis",
 "ordono", "ordonos", "ordonu", "ordonus", "orelo", "oreloj", "organizanto",
 "organizas", "organizi", "organizis", "organizos", "organizu", "organizus",
 "orienten", "oriento", "originala", "orikteropo", "ornami", "ornitorinko",
 "oskedo", "ostaro", "osto", "ovingo", "ovoj", "pacema", "paco", "pafi", "pafilo",
 "paganto", "pagas", "pagi", "paĝi", "pagis", "pago", "paĝo", "pagos", "pagu",
 "pagus", "pakaĵo", "pakas", "paki", "pakis", "pako", "pakos", "paku", "pakus",
 "paleontologo", "palpanto", "palpas", "palpi", "palpis", "palpo", "palpos",
 "palpu", "palpus", "panero", "pano", "pansobendo", "pantalono", "pantoflo",
 "pantolono", "papago", "papero", "papilio", "paraŝuto", "pardonanto", "pardonas",
 "pardoni", "pardonis", "pardonon", "pardonos", "pardonu", "pardonus", "parkere",
 "parko", "parlamenta", "parlamentano", "paro", "parolado", "parolanto", "parolas", "parole",
 "parolema", "paroli", "parolis", "parolo", "parolos", "parolu", "parolus",
 "parteto", "parto", "pasanto", "paŝanto", "pasas", "paŝas", "paŝe", "pasero",
 "pasi", "paŝi", "pasis", "paŝis", "paso", "paŝo", "pasos", "paŝos", "pastro",
 "pasu", "paŝu", "pasus", "paŝus", "patrino", "patro", "peco", "pecoj", "penanto",
 "penas", "pendanto", "pendas", "pendi", "pendis", "pendos", "pendu", "pendus",
 "peni", "penis", "peno", "penos", "pensanto", "pensas", "pensema", "pensi",
 "pensis", "penso", "pensoj", "pensos", "pensu", "pensus", "pentraĵo", "pentranto",
 "pentras", "pentri", "pentris", "pentristo", "pentros", "pentru", "pentrus",
 "penu", "penus", "percepta", "percepto", "perdanto", "perdas", "perdi", "perdis",
 "perdo", "perdos", "perdu", "perdus", "perfekta", "perfekteco", "peri", "periodo",
 "permedi", "permesanto", "permesas", "permesi", "permesis", "permeso", "permesos",
 "permesu", "permesus", "persono", "personoj", "persvadi", "pesi", "petado", "petalo",
 "petanto", "petas", "peti", "petis", "peto", "petos", "petu", "petus", "pezanto",
 "pezas", "pezeco", "pezi", "pezis", "pezos", "pezu", "pezus", "piedbati",
 "piedfingro", "piedfingroj", "piedmigradi", "piedo", "piedoj", "pikanto", "pikas",
 "piki", "pikis", "piko", "pikos", "piku", "pikus", "pilko", "pilolo", "pingvino",
 "pinto", "pipro", "pirato", "piro", "plaĉanto", "plaĉas", "plaĉe", "plaĉi",
 "plaĉis", "plaĉo", "plaĉos", "plaĉu", "plaĉus", "plafono", "plafonoj", "plaĝo",
 "planko", "plankoj", "plano", "planoj", "planti", "planto", "plantoj", "plasta",
 "plasto", "plej", "plejparta", "plejparte", "plena", "plendado", "plendanto",
 "plendas", "plendema",
 "plendi", "plendis", "plendo", "plendos", "plendu", "plendulo", "plendus",
 "plenega", "plenkreskulo", "plenplena", "plenumas", "plenumi", "plenumis",
 "plenumos", "plenumu", "plenumus", "plezura", "plezure", "plezuro", "pliboniĝo",
 "ploras", "plori", "ploris", "ploros", "ploru", "plorus", "plumo", "plumoj",
 "pluraj", "plus", "pluvarbaro", "pluvas", "pluve", "pluvi", "pluvis", "pluvo",
 "pluvos",
 "pluvu", "pluvus", "poemo", "poento", "poentoj", "poezio", "pojno", "policano",
 "policestro", "policisto", "polico", "politikistino", "politikisto", "politiko",
 "poluso", "polvero", "polvo", "polvosuĉilo", "pomo", "pompa", "pontlingvo",
 "ponto", "popolo", "popoloj", "populara", "populareco", "pordego", "pordisto",
 "pordo", "pordoj", "porkaĵo", "porko", "portanto", "portas", "porti", "portis",
 "portos", "portu", "portus", "posedanto", "poŝo", "poŝoj", "post", "poste",
 "poŝtelefono", "posteno", "poŝtisto", "poŝtkesto", "poŝto", "poŝtoficejo",
 "postulanto", "postulas", "postulema", "postuli", "postulis", "postulo",
 "postulos", "postulu", "postulus", "potenca", "poto", "potoj", "povanto", "povas",
 "povi", "povis", "povo", "povos", "povu", "povus", "praavo", "pragmata", 
  "prahistoria", "prahistorio", "praktika",
 "praktike", "praktiko", "pramhaltejo", "pramo", "prauloj", "prava", "pravanto",
 "pravas", "prave", "pravi", "pravis", "pravos", "pravu", "pravus", "precioza",
 "precipa", "precipe", "preciza", "preferas", "preferi", "preferis", "prefero",
 "preferos", "preferu", "preferus", "preĝanto", "preĝas", "preĝejo", "preĝi",
 "preĝis", "preĝos", "preĝu", "preĝus", "preleganto", "prelegas", "prelegi",
 "prelegis", "prelego", "prelegos", "prelegu", "prelegus", "premado", "premanto",
 "premas", "premi", "premiito", "premio", "premioj", "premis", "premkaresi",
 "premos", "premu", "premus", "prenanto", "prenas", "preni", "prenis", "prenos",
 "prenu", "prenus", "preparado", "preparanto", "preparas", "prepari", "preparis",
 "preparos", "preparu", "preparus", "presado", "presaĵo", "presanto", "presas",
 "presi", "presis", "preskaŭ", "presos", "presu", "presus", "preta", "pretas",
 "preter", "preti", "pretiĝas", "pretiĝi", "pretiĝis", "pretiĝos", "pretiĝu",
 "pretiĝus", "pretis", "pretos", "pretus", "prezentanto", "prezentas", "prezenti",
 "prezentis", "prezento", "prezentos", "prezentu", "prezentus", "prezidanto",
 "prezidas", "prezidento", "prezidi", "prezidis", "prezidos", "prezidu", "prezidus",
 "prezo", "prezoj", "principo", "principoj", "printempe", "printempo", "pritondi", 
    "pritraktado", "privata", "problemo",
 "problemoj", "produktanto", "produktas", "produkti", "produktis", "produktos",
 "produktu", "produktus", "profita", "profunda", "profundaj", "profundeco",
 "programas", "programi", "programis", "programisto", "programo", "programoj",
 "programos", "programu", "programus", "progresa", "progresanto", "progresas",
 "progresi", "progresis", "progreso", "progresos", "progresu", "progresus",
 "projeckto", "projekto", "projektoj", "prokrastado", "prokrastema",
 "prokrastita", "prokrastis", "proksima",
 "proksime", "proksimeco", "proksimiĝas", "proksimiĝi", "proksimiĝis", "proksimiĝos",
 "proksimiĝu", "proksimiĝus", "promenanto", "promenas", "promeni", "promenis",
 "promeno", "promenos", "promenu", "promenus", "promesanto", "promesas", "promesi",
 "promesis", "promeso", "promesos", "promesu", "promesus", "proponanto",
 "proponas", "proponi", "proponis", "propono", "proponos", "proponu", "proponus",
 "propra", "propraj", "prosperi", "provanto", "provas", "provi", "provis", "provo",
 "provos", "provu", "provus", "pruno", "prunte", "pruntedonas", "pruntedoni",
 "pruntedonis", "pruntedonos", "pruntedonu", "pruntedonus", "prunteprenas",
 "pruntepreni", "prunteprenis", "prunteprenos", "prunteprenu", "prunteprenus",
 "psikologo", "publika", "publikaj", "publiko", "pulmoj", "punanto", "punas",
 "puni", "punis", "punkto", "puno", "punos", "punu", "punus", "pupo", "pura",
 "puraj", "pureco", "purigi", "purpura", "puŝanto", "puŝas", "puŝi", "puŝis",
 "puŝo", "puŝos", "puŝu", "puŝus", "rabobesto", "racia", "radiko", "radio",
 "radiostacio", "rado", "radoj", "rajdi", "rajtas", "rajti", "rajtis", "rajto",
 "rajtos", "rajtus", "rakontanto", "rakontas", "rakonti", "rakontis", "rakonto",
 "rakontos", "rakontu", "rakontus", "rando", "rango", "rano", "rapida", "rapidaj",
 "rapide", "rapideco", "raportanto", "raportas", "raporti", "raportis", "raporto",
 "raportos", "raportu", "raportus", "rato", "razi", "razio", "razkapulo",
 "redaktanto",
 "redaktas", "redakti", "redaktis", "redaktistino", "redaktos", "redaktu", "redaktus",
 "reganto", "regas", "regi", "reĝido", "regilo", "reĝimo", "reĝino", "regiono", "regionoj",
 "regis", "reĝisoro", "registaro", "reĝo", "regos", "regu", "regulo", "reguloj",
 "regus", "reklamo", "rekomenco", "rekomendas", "rekomendi", "rekomendis",
 "rekomendo", "rekomendos", "rekomendu", "rekomendus", "rekonstrui", "rekta",
 "rekten", "rektigilo", "religiano", "religio", "religioj", "reloki", "remarŝi", "remi",
 "renkontanto", "renkontas", "renkonti", "renkontis", "renkonto", "renkontos",
 "renkontu", "renkontus", "reno", "renoma", "reptilo", "resendi", "respekti",
 "respondanto", "respondas", "respondi", "respondis", "respondo", "respondos",
 "respondu", "respondulo", "respondus", "restanto", "restantoj", "restas", "resti",
 "restis", "resto", "restoracio", "restos", "restu", "restus", "resume", "retpaĝo",
 "retroviŝo", "retumi", "revado", "revemo", "revi", "revuo", "rezigno", "rezona",
 "rezultas", "rezulti", "rezultis", "rezulto", "rezultos", "rezultu", "rezultus",
 "riĉa", "riĉaj", "riĉeco", "riĉega", "ricevanto", "ricevas", "ricevi", "ricevis",
 "ricevita", "ricevos", "ricevu", "ricevus", "riĉulo", "ridas", "ridetas",
 "rideti", "ridetis", "rideto", "ridetos", "ridetu", "ridetus", "ridi", "ridis",
 "rido", "ridos", "ridu", "ridus", "rigardanto", "rigardas", "rigardi", "rigardis",
 "rigardo", "rigardos", "rigardu", "rigardus", "rilatas", "rilati", "rilatis",
 "rilato", "rilatos", "rilatu", "rilatus", "rimarkas", "rimarki", "rimarkis",
 "rimarko", "rimarkos", "rimarku", "rimarkus", "rimedo", "rimedoj", "rimeno",
 "rinocero", "ripetanto", "ripetas", "ripeti", "ripetis", "ripeto", "ripetos",
 "ripetu", "ripetus", "ripozanto", "ripozas", "ripozi", "ripozis", "ripozo",
 "ripozos", "ripozu", "ripozus", "rivereto", "rivero", "riveroj", "rizo", "robo",
 "roboj", "roboto", "robotoj", "roko", "romanisto", "romano", "romanoj", "rompas", "rompi", "rompiĝas",
 "rompiĝi", "rompiĝis", "rompiĝos", "rompiĝus", "rompis", "rompita", "rompos",
 "rompu", "rompus", "rondo", "rondoj", "rondokule", "roso", "rosti", "rozkolora",
 "rozo", "rozoj", "rubeno", "rubo", "rubriko", "rudimenta", "rufa", "ruĝa",
 "ruĝiĝas", "ruĝiĝi", "ruĝiĝis", "ruĝiĝos", "ruĝiĝus", "rulas", "ruli", "rulis",
 "rulo", "rulos", "rulu", "rulus", "ruza", "sabate", "sabato", "sablero", "sablo",
 "ŝafaro", "ŝafido", "ŝafino", "safiro", "ŝafisto", "ŝafo", "ŝafoj", "saĝa",
 "sago", "saĝtelefono", "saĝulo", "ŝajnas", "ŝajni", "ŝajnis", "ŝajnos", "ŝajnu",
 "ŝajnus", "saketo", "sako", "salato", "salikoko", "salo", "salono", "saltanto",
 "saltas", "saltema", "salteto", "salti", "saltis", "salto", "saltos", "saltu",
 "saltus", "ŝalupo", "salutanto", "salutas", "saluti", "salutis", "saluton",
 "salutos",
 "salutu", "salutus", "sama", "samideano", "sana", "ŝanco", "sandalo", "sandviĉo",
 "ŝanĝanto", "ŝanĝas", "ŝanĝi", "ŝanĝiĝas", "ŝanĝiĝi", "ŝanĝiĝis", "ŝanĝiĝos",
 "ŝanĝiĝu", "ŝanĝiĝus", "ŝanĝis", "sango", "ŝanĝo", "ŝanĝos", "ŝanĝu", "ŝanĝus",
 "sankta", "sankto", "sardelo", "sarkasmo", "sata", "ŝatanto", "ŝatas", "satelito", "ŝati",
 "ŝatis", "ŝatita", "ŝato", "ŝatos", "ŝatu", "ŝatus", "savanto", "savas", "savi",
 "savis", "savos", "savu", "savus", "scias", "scienca", "sciencisto",
 "sciencistoj", "scienco", "scientisto", "scii", "sciis", "scio", "scios", "sciu",
 "sciuro", "scius", "scivolas", "scivolema", "scivoli", "scivolis", "scivolos",
 "scivolus", "seĝo", "seĝoj", "seka", "sekegeco", "sekiĝas", "sekiĝi", "sekigilo",
 "sekiĝis", "sekiĝos", "sekiĝus", "sekretario", "sekretema", "sekso", "sekundo",
 "sekura", "sekurigo", "sekvanto", "sekvas", "sekvi", "sekvis", "sekvo", "sekvos",
 "sekvu", "sekvus", "semajnfino", "semajno", "semajnoj", "sencela", "senco",
 "sendanĝera", "sendanto", "sendas", "senfina", "senfine", "sendi", "sendis",
 "sendos", "sendu",
 "sendube", "sendus", "senkonscia", "senkulpa", "senprecedenca", "senprobleme",
 "senrekona", "sentas", "sentema", "senti", "sentima", "sentis", "sento",
 "sentos", "sentu", "sentus", "septembro", "serĉado", "serĉanto", "ŝercanto",
 "serĉas", "ŝercas", "ŝercema", "ŝercemaj", "serĉi", "ŝerci", "serĉis", "ŝercis",
 "serĉita", "serĉo", "ŝerco", "serĉos", "ŝercos", "serĉu", "ŝercu", "serĉus",
 "ŝercus", "serio", "serioj", "serioza", "serpento", "servanto", "servas",
 "servi", "servis", "servisto", "servo", "servos", "servu", "servus", "sezono",
 "sezonoj", "sidanto", "sidas", "sidi", "sidiĝas", "sidiĝi", "sidiĝis", "sidiĝos",
 "sidiĝu", "sidiĝus", "sidis", "sidos", "sidu", "sidus", "sieĝo", "signifas",
 "signifi", "signifis", "signifo", "signifoj", "signifos", "signifu", "signifus",
 "signo", "signoj", "silentas", "silentema", "silenti", "silentis", "silento",
 "silentos", "silentu", "silentus", "simila", "simio", "simpla", "simplaj",
 "simpleco", "sinjorino", "sinjoro", "ŝipestro", "ŝipisto", "ŝipo", "ŝiranto",
 "ŝiras", "ŝiri", "ŝiris", "ŝiros", "ŝiru", "ŝirus", "sistemo", "sistemoj",
 "sitelo", "situacio", "skandalo", "skandi", "skatolo", "skatoloj", "skrapi",
 "skribaĵo", "skribanto", "skribas", "skribi", "skribis", "skribisto", "skribos",
 "skribu", "skribus", "skulptisto", "ŝlosas", "ŝlosi", "ŝlosilo", "ŝlosis",
 "ŝlosos", "ŝlosu", "ŝlosus", "smeraldo", "ŝnuro", "socia", "socio", "sofo",
 "soifanto", "soifas", "soifi", "soifis", "soifo", "soifos", "soifu", "soifus",
 "sola", "soldato", "soldatoj", "soleca", "soleno", "solvas", "solvi", "solviĝas",
 "solviĝi", "solviĝis", "solviĝos", "solviĝus", "solvis", "solvo", "solvos",
 "solvu", "solvus", "somero", "sonas", "soni", "sonis", "sono", "sonos", "sonu",
 "sonus", "sorbi", "sovaĝa", "sovaĝejo", "ŝparema", "speciala", "specialaj",
 "specimeno", "speco", "specoj", "spegulaĵo", "spegulo", "sperta", "spertas",
 "sperti", "spertis", "spertos", "spertu", "spertulo", "spertus", "spezo",
 "spica", "spico", "spino", "spirado", "spiranto", "spiras", "spiri", "spiris",
 "spirito", "spiro", "spiros", "spiru", "spirus", "sportema", "sportisto", "sporto",
 "sportoj", "ŝranko", "ŝraŭbilo", "ŝraŭbo", "stacio", "staciodomo",
 "ŝtalo", "staranto", "staras", "stari", "starigas", "starigi", "starigis",
 "starigos", "starigus", "staris", "staros", "staru", "starus", "statistiko",
 "stato", "ŝtato",
 "statuo", "ŝtelado", "ŝtelanto", "stelaro", "ŝtelas", "ŝteli", "ŝtelis",
 "ŝtelisto", "ŝtelita", "stelo", "ŝtelos", "ŝtelu", "stelulo", "ŝtelus",
 "stereotipo", "stevardo", "ŝtipo", "ŝtofo", "ŝtona", "ŝtono", "stranga",
 "strangaj",
 "strangeco", "strangulo", "stratangulo", "stratanguloj", "strateto", "stratetoj",
 "stratmuzikisto", "stratmuzikistoj", "strato", "stratoj", "streĉanto", "streĉas",
 "streĉi", "streĉis", "streĉo", "streĉos", "streĉu", "streĉus", "strigo", "strio",
 "strukturo", "ŝtrumpeto", "ŝtrumpetoj", "ŝtrumpo", "struto", "studanto",
 "studantoj", "studas", "studema", "studemaj", "studento", "studi", "studis",
 "studo", "studos", "studu", "studus", "stulta", "stulteco", "stulteta",
 "stultulo", "ŝtuparo", "ŝtupo", "subita", "subite", "subtaso", "subtila",
 "subvestoj",
 "suĉi", "suda", "suden", "sudo", "suferado", "suferanto", "suferas", "suferi",
 "suferis", "suferos", "suferu", "suferus", "sufiĉa", "sufiĉas", "sufiĉe",
 "sufiĉi", "sufiĉis", "sufiĉos", "sufiĉus", "sukcesa", "sukcesaj", "sukcesas",
 "sukcesi", "sukcesis", "sukceso", "sukcesos", "sukcesu", "sukcesus", "sukeraĵo",
 "sukeraĵoj", "sukero", "suko", "ŝultro", "sumo", "sunbrilo", "sune", "suno",
 "ŝuoj", "super", "supereco", "superflua", "superforti", "supo", "supozanto",
 "supozas", "supozebla", "supozi", "supozis", "supozo", "supozos", "supozu",
 "supozus", "supre", "supren", "supro", "surda", "surportas", "surporti",
 "surportis", "surportos", "survoje", "suspektema", "ŝuti", "ŝveligebla",
 "ŝveligita", "svingi", "ŝvitado",
 "tablo", "tablotuko", "tabulo", "tagmanĝo", "tagmezo", "tago", "tagoj",
 "tajdo", "tajpi", "taksiisto", "takso", "talaro", "talio", "tamen", "tapiŝo",
 "tasko", "taskoj", "taso", "tasoj", "taŭga", "taŭganto", "taŭgas", "taŭgi",
 "taŭgis", "taŭgos", "taŭgu", "taŭgus", "taŭro", "teamo", "teatraĵo", "teatro",
 "teatrumi", "tedi", "teejo", "tegmento", "tegmentoj", "teĥnika", "tekniko",
 "teknologio", "tekruco", "teksto", "telefonas", "telefoni", "telefonis",
 "telefono", "telefonos", "telefonu", "telefonus", "teleraro", "telero",
 "teleroj", "televida", "televidilo", "televido", "temas", "temi", "temis",
 "temo", "temoj", "temos", "tempo", "temus", "tenado", "tenanto", "tenas",
 "tendo", "teni", "tenilo", "tenis", "teniso", "teno", "tenos", "tenu", "tenus",
 "teoj", "teorie", "teorio", "teorioj", "terano", "terapeŭtika", "tero", "tertremo", "terura",
 "terure", "teruro", "tesaketo", "tetaso", "teumi", "tiaj", "tiajn", "tial",
 "tiam", "tian", "tiel", "tien", "ties", "tigro", "timanto", "timas", "timema",
 "timemaj", "timi", "timiga", "timiĝas", "timiĝi", "timiĝis", "timiĝos",
 "timiĝus", "timis", "timo", "timos", "timu", "timus", "tineo", "tiom", "tion",
 "tipo", "tirado", "tiranto", "tiras", "tiri", "tiris", "tiro", "tiros", "tiru",
 "tirus", "tiuj", "tiujn", "tiun", "tondanto", "tondas", "tondi", "tondilo",
 "tondis", "tondo", "tondos", "tondri", "tondro", "tondu", "tondus", "tono",
 "tradicia", "tradiciaj", "tradicio", "tradukanto", "tradukas", "traduki",
 "tradukinda", "tradukis", "tradukisto", "traduko", "tradukos", "traduku",
 "tradukus", "trafanto", "trafas", "trafi", "trafiklumo", "trafiko", "trafis",
 "trafos", "trafu", "trafus", "traktanto", "traktas", "trakti", "traktis",
 "traktos", "traktu", "traktus", "tramhaltejo", "tramo", "trampolino",
 "tranĉanto", "tranĉas",
 "tranĉi", "tranĉilo", "tranĉis", "tranĉo", "tranĉos", "tranĉu", "tranĉus",
 "trankvila", "trankvileco", "trankviliĝas", "trankviliĝi", "trankviliĝis",
 "trankviliĝos", "trankviliĝu", "trankviliĝus", "tranoktas", "tranokti",
 "tranoktis", "tranoktos", "tranoktus", "trans", "translokigi", "traserĉi", "traŭmo",
 "travivas", "travivi", "travivis", "travivos", "travivus", "trejnisto", "trejno",
 "triki", "trinkaĵo", "trinkanto", "trinkas", "trinki", "trinkis", "trinkos",
 "trinku", "trinkus", "trioble", "trista", "tritiko", "triumfo", "trivi", "triviala",
 "trompo", "trotuaro", "trovanto", "trovas", "trovi", "troviĝas", "troviĝi",
 "troviĝis",
 "troviĝos", "troviĝus", "trovis", "trovos", "trovu", "trovus", "truo", "truoj",
 "tuko", "tulipo", "turismo", "turisto", "turistoj", "turmentita", "turnanto",
 "turnas", "turni", "turniĝas", "turniĝi", "turniĝis", "turniĝos", "turniĝu",
 "turniĝus", "turnis", "turno", "turnos", "turnu", "turnus", "turo", "turto",
 "tuŝanto", "tuŝas", "tuŝema", "tusi", "tuŝi", "tuŝis", "tuŝo", "tuŝos", "tuŝu",
 "tuŝus", "tuta", "tutcerte", "tuto", "ublieto", "ungo", "universala", "universitato",
 "universo", "uragano", "urba", "urbestro", "urbo", "urbulo", "urĝe", "urini",
 "urso", "utila", "utilas", "utili", "utiliĝas", "utiliĝi", "utiliĝis", "utiliĝos",
 "utiliĝus", "utilis", "utilos", "utilus", "uzanto", "uzantoprofilo", "uzas",
 "uzata", "uzatas", "uzebla", "uzis", "uzita", "uzos", "uzus", "vagadi",
 "vagonaro", "vagono", "vagonoj", "vakuo", "valida", "validas", "validi",
 "validis", "validos", "validus", "valizo", "valo", "valora", "valoras", "valori",
 "valoris", "valoro", "valoros", "valorus", "vango", "varbi", "varianto", "varma", "varme",
 "varmeco", "varmega", "varmeta", "varmiĝas", "varmiĝi", "varmiĝis", "varmiĝos",
 "varmiĝus", "vartestino", "vasta", "vasteco", "vekado", "vekanto", "vekas",
 "veki", "vekis", "vekos", "veku", "vekus", "velka", "velkanta", "venanto",
 "venas", "vendanto", "vendas", "vendejo", "vendi", "vendis", "vendisto", "vendo",
 "vendos", "vendrede", "vendredo", "vendu", "vendus", "venĝe", "venĝo", "veni",
 "venis", "venkanto", "venkas", "venki", "venkintoj", "venkis", "venko", "venkos",
 "venku", "venkus", "venonta", "venontaj", "venos", "venta", "ventego", "venteto",
 "vento", "ventro", "ventumilo", "venu", "venus", "vera", "verda", "verkanto",
 "verkas", "verkema", "verki", "verkis", "verkisto", "verko", "verkos", "verku",
 "verkus", "verŝajne", "verŝi", "vespermanĝas", "vespermanĝi", "vespermanĝis",
 "vespermanĝo", "vespermanĝos", "vespermanĝu", "vespermanĝus", "vespero",
 "vesperto", "vestaĵo", "vestas", "vesti", "vestiĝas", "vestiĝi", "vestiĝis",
 "vestiĝos", "vestiĝu", "vestiĝus", "vestis", "vesto", "vestos", "vestu",
 "vestus", "vetero", "veturado", "veturanto", "veturas", "veturi", "veturis",
 "veturisto", "veturo", "veturos", "veturu", "veturus", "viando", "vice", "vico",
 "vidaĵo", "vidanto", "vidas", "videbla", "vidi", "vidigo", "vidiĝo", "vidinda",
 "vidindaĵo", "vidinte", "vidis", "vido", "vidos", "vidu", "vidus", "vigla",
 "viktimo", "vilaĝano", "vilaĝo", "vinbotelo", "vino", "vintro", "violkolora",
 "violo", "vira", "virbovo", "virino", "viro", "virŝafo", "viruso", "viŝanto",
 "viŝas", "viŝi", "viŝis", "viskio", "viŝos", "viŝu", "viŝus", "vitra", "vitro",
 "viva", "vivaj", "vivanto", "vivas", "vivi", "vivis", "vivo", "vivos", "vivu",
 "vivus", "vizaĝo", "vizaĝalherbe", "vizitadi", "vizitanto", "vizitas", "viziti",
 "vizitinte",
 "vizitis", "vizito", "vizitos", "vizitu", "vizitus", "voĉo", "vojaĝanto",
 "vojaĝas", "vojaĝema", "vojaĝi", "vojaĝis", "vojaĝo", "vojaĝos", "vojaĝu",
 "vojaĝus", "vojo", "vojoj", "vokanto", "vokas", "voki", "vokis", "voko", "vokos",
 "voku", "vokus", "volanto", "volapukaĵo", "volas", "voli", "volis", "volo",
 "volonte", "volos", "volu", "volus", "volvanto", "volvas", "volvi", "volviĝi",
 "volvis", "volvos", "volvu", "volvus", "vombato", "vortaro", "vortludo", "vorto",
 "vortoj", "vortostoko", "vosto", "vostoj", "vrako", "vulkano", "vulpo", "vundi",
 "vundo", "zammenhof", "zombio", "zono", "zorganto", "zorgas"
  
];
